### ISSUE TITLE
Install of read the docs

### ISSUE THREAD

**Issue by Ennazus** [psrc/soundcast#128]

**Comment by bricegnichols** [comment]
Work in progress, but it's installed and being used to create a User's Guide. [Latest build here](ttp://soundcast.readthedocs.org/en/dev/docs/)

**Comment by billyc** [comment]
This already looks about 1000x better than anything documentation we've ever produced.  Thanks Brice!

**Comment by Ennazus** [comment]
This is looking really great!! I thought we couldn't get anything 1/10th this good in two days.  Let's plan on showing this at the RTF as well.  I'll do that at the end my presentation like, learn more- here are some resources: this document, github, and our webpage.
