### ISSUE TITLE
Split run_soundcast.py into two: prepare & run 

### ISSUE THREAD

**Issue by billyc** [psrc/soundcast#142]
In order to archive the true inputs, we need to split run_soundcast into two parts:
### Copy inputs and prepare networks
- Existing copy_inputs code should be here
- Network i/o tool functions that convert GDB inputs into Emme-ready files
- Anything else? Someone needs to think about what else might change on our file servers that needs to be archived
- Add a new call to the model archive "freezer" which will snapshot the entire folder and push it to the new git inputs archive.
### Run the model
- Make sure that step 1 worked;
- Then actually run the model.

Some details we'll need to figure out include whether to add a run to the runlog if it was run on a local machine -- seems like the answer is yes but I'm not quite sure the best way to do that yet.

**Comment by Ennazus** [comment]
It seems like we should start doing this now @stefancoe @bricegnichols @billyc I think we need a general soundcast check in to go over all these hanging issues
