### ISSUE TITLE
use rsync and shell to locally cache large inputs

### ISSUE THREAD

**Issue by Ennazus** [psrc/soundcast#187]
Billy's notes:
copy_large_inputs is slow because it copies every file over the network every time. 

I bet most of the files don't change very often. It wouldn't be too hard to create a local hard disk cache of the needed files, and then quickly copy the files from the cache to the model run directory.  Using a tool like rsync would make this go fairly fast and ensure that the most recent files are always used correctly.

It would be a pretty easy shell script to write if someone wants to take it on. Steps would be:

- Generate exact list of files that need to be copied from the network
- Use rsync to create a local cache folder of those files somewhere on the local drive.
- Use rsync a second time to copy the list of files from the cache into the model run directory

The first time, and when many files changed, it would fetch them from the network. But for subsequent runs, only the changed files would be copied over the network. This would have big time savings.

What is rsync
https://en.wikipedia.org/wiki/Rsync

Rsync for Windows is available at 
https://www.itefix.net/cwrsync

We're probably going to use rsync to copy our model run backups into the cloud, so you're going to learn it soon anyway :-)

**Comment by bricegnichols** [comment]
output snapshots happening in queue, testing method to delete and revive banks using h5 output
