### ISSUE TITLE
Create a summary of truck volumes vs counts

### ISSUE THREAD

**Issue by Ennazus** [psrc/soundcast#201]
Hopefully automated summary.

Who should do this?

**Comment by bricegnichols** [comment]
I checked in a notebook that does some aggregate analysis as a start, https://github.com/psrc/soundcast/blob/dev/scripts/summarize/notebooks/trucks.ipynb

**Comment by KrisO67** [comment]
I can attempt to apply my soon-to-be blazing python skills to this task after Suzanne coaches me up next month.
