### ISSUE TITLE
set up way to run only one part of soundcast only!

### ISSUE THREAD

**Issue by Ennazus** [psrc/soundcast#202]
like just daysim
or just assignment

currently we have to run daysim and shadow pricing on every run!
but sometimes we're just testing

maybe different modes of running

**Comment by stefancoe** [comment]
Right, it's a simple fix. I'll take care of it.

On Fri, Mar 25, 2016 at 4:02 PM, Suzanne Childress <notifications@github.com

**Comment by Ennazus** [comment]
I think this is fixed
