### ISSUE TITLE
Go though path weights in config file make sure they make sense for estimation

### ISSUE THREAD

**Issue by stefancoe** [psrc/soundcast#235]
Mode choice models in Daysim typically use mode specific log sums instead of skim values. Components of each mode can be given weights using path-type weight parameters in the config file. This begs the question- which weights to use during estimation, as they will influence the log sum values. For example, right now we have a large weight on the number of boarding in the transit path type model to decrease the attractiveness of transit tours/trips that involve transfers. When estimating, it probably does not make sense to have this high of a weight.

**Comment by bricegnichols** [comment]
I think we settled on zeroing these out for estimation
