### ISSUE TITLE
Remove "run_supplemental_generation" switch for trucks?

### ISSUE THREAD

**Issue by bricegnichols** [psrc/soundcast#345]
@stefancoe do we need this anymore now that we use LODES? It can cause errors if it's accidentally switched off when running different model parts. Robert Tung had that problem last week and I hit it myself just now.

**Comment by stefancoe** [comment]
We should search the code to see where/how this switch is used.

**Comment by bricegnichols** [comment]
closed by https://github.com/psrc/soundcast/commit/380c466cd88cb1739d32a8dc80774d4c6646c384
