### ISSUE TITLE
Implement shared ride mode

### ISSUE THREAD

**Issue by stefancoe** [psrc/soundcast#346]
We started this...so creating an issue to track progress.

**Comment by bricegnichols** [comment]
Testing this using asserted coefficients in daysim_configuration, as well as with additional coefficients added from SACOG model. Results showed 0.9% regional mode share in rideshare, concentrated in downtown Seattle. 

Next steps: 
1. assign these trips to the network https://github.com/psrc/soundcast/issues/288
2. create 2017 survey data for estimation
3. create calibration summaries for rideshare, from soundcast and survey data

**Comment by bricegnichols** [comment]
Tests show this is feasible, want to wrap it in to addition of other modes (AV, maybe EV, others?) Will be reworking this as part of a larger effort: https://github.com/psrc/soundcast/issues/352
