### ISSUE TITLE
test tighter convergence criteria

### ISSUE THREAD

**Issue by bricegnichols** [psrc/soundcast#369]
From INRO:

"As a side note, in the reports you sent to us, the assignment stopped on the normalized gap criterion, which did not allow the model to converge to a 10^-4 relative gap. Was this your intention? It is a good practice to use one and only one criterion, while setting all the others to 0, in order to ensure a uniform convergence of the model across different scenarios and for future years. Nowadays, the industry standard is a relative gap of 10^-4, which implies a best relative gap and normalized gap setting of 0."

**Comment by bricegnichols** [comment]
Test SOLA

**Comment by bricegnichols** [comment]
2014: total run time **13:54:21 (using z6.xlarge)** vs 16:41:56 (using r4.8xlarge) from vision run; 

Assignment times by iteration for longest assignment period: 
tighter convergence | older code
5: 84.2 | 79.5
4: 106.35 | 80.1
3: 69.13 | 63.55

**Comment by stefancoe** [comment]
> 2014: total run time **13:54:21 (using z6.xlarge)** vs 16:41:56 (using r4.8xlarge) from vision run;
> 
> Assignment times by iteration for longest assignment period:
> tighter convergence | older code
> 5: 84.2 | 79.5
> 4: 106.35 | 80.1
> 3: 69.13 | 63.55

Brice- I take it this is not SOLA, just a higher performing machine? Have you been able to compare the results using the tighter settings? Thanks!

**Comment by bricegnichols** [comment]
This is standard path based assignment. The machine z6.xlarge is cheaper but runs Soundcast faster than the r4.8xlarge instance. 

Results are very close on VMT and VHT for 2014:
tighter convergence | older code:
VMT: 79,570,208 | 79,630,384
VHT: 2,391,664 | 2,394,700

**Comment by bricegnichols** [comment]
Re-ran a 2050 Stay the Course run, with z6.xlarge. **30 hour run-time** 

Results: (tighter convergence | Vision run)
VMT: 107,386,643 | 108,025,618
VHT: 3,664,160 | 3,670,228
Delay: 771,596 | 762,523

**Comment by bricegnichols** [comment]
Run times and results are only marginally affected based on these tests - keeping the industry standard and a single criterion
