### ISSUE TITLE
Move all inputs to a database.

### ISSUE THREAD

**Issue by stefancoe** [psrc/soundcast#388]
Can be sqlite for now, maybe elmer down the road.

**Comment by bricegnichols** [comment]
Standard inputs are in a database now, and code updated to use these tables on the dev branch: R:\e2projects_two\SoundCast\Inputs\dev\db

This db is used for all base and model years. Inputs are either queried from db tables or grown at a set rate. Primary inputs are in the **soundcast_inputs.db** file, and validation count data will be stored in **validation.db**.
