### ISSUE TITLE
update roster for tnc to transit

### ISSUE THREAD

**Issue by bricegnichols** [psrc/soundcast#392]
if TNC is unavailable don't add TNC to transit mode in the roster

**Comment by bricegnichols** [comment]
closes e01663cbf856739c45620656b19c62d1ec757b46

**Comment by msimonson-psrc** [comment]
@hanase @bricegnichols @stefancoe Saw this and wondered about UrbanSim-2, Python 3.X and compatibility.  Flagging for coordination.
