### ISSUE TITLE
update corridor travel times

### ISSUE THREAD

**Issue by bricegnichols** [psrc/soundcast#399]
Google API is no longer free, need some other source. Maybe HPMS, INRIX, or Uber for 2018

**Comment by msimonson-psrc** [comment]
What sort of costs are we looking at now Brice?

**Comment by bricegnichols** [comment]
I think we can replace this without paying anything. The pricing is potentially free if we stay under a certain number of requests, but a card is now required on file to access the API at all. I think there also might be better sources anyway that give us historical (2018) data other than Google.

**Comment by bricegnichols** [comment]
Add corridors to geodatabase to compare to INRIX data

**Comment by bricegnichols** [comment]
Added corridor speed from link-based data now stored in soundcast_db

example summary at bottom: https://github.com/psrc/soundcast/blob/dev/scripts/summarize/notebooks/validation.ipynb
