### ISSUE TITLE
Duplicate parameter in emme_configuration

### ISSUE THREAD

**Issue by stefancoe** [psrc/soundcast#414]
Since we will most likely always skim for every transit time period, we probably don't need both. 

load_transit_tod = ['5to6', '6to7', '7to8', '8to9', '9to10', '10to14', '14to15', '15to16', '16to17', '17to18', '18to20']

transit_skim_tod = ['5to6', '6to7', '7to8', '8to9', '9to10', '10to14', '14to15', '15to16', '16to17', '17to18', '18to20']

**Comment by bricegnichols** [comment]
Looks like this was taken care of by removing both and using a new var **transit_tod_list**
