### ISSUE TITLE
Create a work at home summary

### ISSUE THREAD

**Issue by stefancoe** [psrc/soundcast#428]
-Include percent of workers that work from home
-Would be cool to tag them to be able to run summaries about them, like tours/trips by purpose.

**Comment by bricegnichols** [comment]
created new HTML output:
- total work from home workers by county vs survey
- tour rate for WFH workers

https://github.com/psrc/soundcast/blob/dev/scripts/summarize/notebooks/work.ipynb

https://github.com/psrc/soundcast/commit/5560035a6f955fb87eb85ee9ce8dfbc00c5e127e
