### ISSUE TITLE
Complete DayPattern Notebook 

### ISSUE THREAD

**Issue by stefancoe** [psrc/soundcast#463]
Could include:

- Tours Per Person,
- Tours Per Person By Purpose
- Percent of Tours by Purpose
- Tours by Person Type, by Purpose
- Work-Based Subtour Generation
See old DayPatternReport.xlsx here:
V:\T2040\soundcast_2006\outputs
V=model archive drive

**Comment by bricegnichols** [comment]
https://github.com/psrc/soundcast/commit/2e4e7ea19726430f4706fd89d91aa73279a95909

https://github.com/psrc/soundcast/blob/dev/scripts/summarize/notebooks/validation/day_pattern.ipynb

Also: https://github.com/psrc/soundcast/blob/dev/scripts/summarize/notebooks/validation/intermediate_stop_generation.ipynb
