### ISSUE TITLE
Complete Tour Destination notebook

### ISSUE THREAD

**Issue by stefancoe** [psrc/soundcast#464]
Include:

- Avg Distance By Tour Purpose
- Avg Distance By Tour Mode
- Trips Per Tour By Tour Purpose
- Trips Per Tour By Tour Mode
- Percent Tours by Destination District.

**Comment by bricegnichols** [comment]
https://github.com/psrc/soundcast/commit/2e4e7ea19726430f4706fd89d91aa73279a95909

https://github.com/psrc/soundcast/blob/dev/scripts/summarize/notebooks/validation/tour_destination.ipynb
