### ISSUE TITLE
Complete Trip Generation/Location Notebook

### ISSUE THREAD

**Issue by stefancoe** [psrc/soundcast#465]
Summarizes the intermediate stop generation and location models. 
Include:

- Avg Dist by Trip Mode
- Avg Dist by Trip Purpose
- % Trips by Destination District

**Comment by bricegnichols** [comment]
https://github.com/psrc/soundcast/commit/2e4e7ea19726430f4706fd89d91aa73279a95909

https://github.com/psrc/soundcast/blob/dev/scripts/summarize/notebooks/validation/trip_destination.ipynb
