### ISSUE TITLE
Tour & Trip Mode Notebook

### ISSUE THREAD

**Issue by stefancoe** [psrc/soundcast#466]
- Tour/Trip Mode Share
- Tour/Trip Mode Share By Purpose
- Others?

**Comment by bricegnichols** [comment]
https://github.com/psrc/soundcast/commit/2e4e7ea19726430f4706fd89d91aa73279a95909

https://github.com/psrc/soundcast/blob/dev/scripts/summarize/notebooks/validation/tour_mode.ipynb

https://github.com/psrc/soundcast/blob/dev/scripts/summarize/notebooks/validation/trip_mode.ipynb
