### ISSUE TITLE
TOD mapping for hourly counts in validation script

### ISSUE THREAD

**Issue by goreaditya** [psrc/soundcast#493]
It appears that the hour to [tod mapping](https://github.com/psrc/soundcast/blob/35faa3ea606f22e30a40256ef585d555a2de45d2/scripts/summarize/standard/validation.py#L67#L91) for value 20 is incorrect. Currently it is set to '18to20' but should be associated with '20to5' based on other values in the dictionary.
https://github.com/psrc/soundcast/blob/35faa3ea606f22e30a40256ef585d555a2de45d2/scripts/summarize/standard/validation.py#L87

This can be fixed by replacing the line with the following:
`20:'20to5',`

Please add any notes here if my interpretation of tod_lookup is incorrect.

**Comment by bricegnichols** [comment]
Thanks for noting this @goreaditya! I patched that with https://github.com/psrc/soundcast/commit/d7ba97e2269f8f642e36722d412181c8b6663573
