### ISSUE TITLE
Day Pattern Validation Notebooks- add tours per person by person type for each tour purpose

### ISSUE THREAD

**Issue by stefancoe** [psrc/soundcast#530]
We have this for work tours, but need it for all purposes. 

![newplot (2)](https://github.com/psrc/soundcast/assets/1302855/ef275b1a-05c5-487b-8bda-fe1ecc3c6f81)

**Comment by stefancoe** [comment]
Section 2.3 in the telecommute summary notebook has a good example of this. but slightly different. It has tab for commuter, teleworker and work from home and the chart shows tour purpose on the X axis and tour rates on the Y.

**Comment by bricegnichols** [comment]
https://github.com/psrc/soundcast/commit/3953beef4f9daf0339f51aa4e3e52ec1e9be94a2
