### ISSUE TITLE
Inconsistency in Assignment Time Period (15to16)

### ISSUE THREAD

**Issue by PaudelXA** [psrc/soundcast#544]
https://github.com/psrc/soundcast/wiki/Network#network-assignment assigns **15to16 as Mid-Day**
https://github.com/psrc/soundcast/blob/master/configuration/network_configuration.toml#L95C1-L109C15 **Line 105 assigns 15to16 as PM**

**Comment by bricegnichols** [comment]
Thanks for the catch. The wiki is updated to reflect 15to16 as PM

https://github.com/psrc/soundcast/wiki/Network/ea233edcc36d3a778af1571f9bd3cbc80db061a8
